/** 桌面云端登录只接受客户，过期及跨客户检查不会停止 Agent。 */
import { it, expect, vi } from "vitest";
import { DesktopAuth } from "../electron/auth";
/** 合成令牌不涉及真实账号。 */
const reply=()=>Response.json({token:"a".repeat(64),user:{username:"testcustomer",role:"customer"},expires:Date.now()+60000});
it("starts locked and rejects invalid input without network",async()=>{const request=vi.fn();const a=new DesktopAuth(request);expect(a.session().authenticated).toBe(false);await expect(a.require()).rejects.toThrow();expect((await a.login({},{})).ok).toBe(false);expect(request).not.toHaveBeenCalled();});
it("accepts customer only and hides token from renderer",async()=>{const request=vi.fn().mockResolvedValueOnce(reply()).mockResolvedValue(Response.json({user:{username:"testcustomer",role:"customer"}}));const a=new DesktopAuth(request);expect((await a.login("testcustomer","synthetic-secret")).ok).toBe(true);expect(a.session()).toEqual({authenticated:true,username:"testcustomer"});await a.require("pc_test");expect(request.mock.calls[1][0]).toContain("agentId=pc_test");await a.logout();expect(a.session().authenticated).toBe(false);});
it("rejects admin and expired or foreign-device sessions",async()=>{const a=new DesktopAuth(vi.fn().mockResolvedValue(Response.json({error:"管理员请使用管理员网页端。"},{status:403})));expect((await a.login("testadmin","synthetic-secret")).message).toContain("管理员");const request=vi.fn().mockResolvedValueOnce(reply()).mockResolvedValue(Response.json({},{status:403}));const customer=new DesktopAuth(request);await customer.login("testcustomer","synthetic-secret");await expect(customer.require("pc_other")).rejects.toThrow("分配");expect(customer.session().authenticated).toBe(true);});
it("reports offline login clearly",async()=>{const a=new DesktopAuth(async()=>{throw new Error("private network detail");});expect((await a.login("customer","synthetic-secret")).message).toContain("网络");});

/** 服务故障不能删除客户会话，但敏感调用仍被拒绝。 */
it.each([429,500,503])("preserves customer login on HTTP %s",async status=>{const request=vi.fn().mockResolvedValueOnce(reply()).mockResolvedValue(new Response("upstream private",{status}));const auth=new DesktopAuth(request);await auth.login("customer","synthetic");await expect(auth.require("pc_a")).rejects.toMatchObject({code:"CLOUD_UNAVAILABLE"});expect(auth.session().authenticated).toBe(true);});
it("locks only a confirmed expired customer session",async()=>{const request=vi.fn().mockResolvedValueOnce(reply()).mockResolvedValue(new Response("",{status:401}));const auth=new DesktopAuth(request);await auth.login("customer","synthetic");await expect(auth.require()).rejects.toMatchObject({code:"AUTH"});expect(auth.session().authenticated).toBe(false);});
