/** 扫描覆盖多盘候选、中文路径、重复路径、不完整目录和取消反馈。 */
import {mkdtemp,mkdir,writeFile,rm,realpath} from "node:fs/promises";import path from "node:path";import os from "node:os";
import {it,expect,vi} from "vitest";
const mocks=vi.hoisted(()=>({drives:[] as string[],paths:[] as string[]}));
vi.mock("node:util",()=>({promisify:()=>async(_exe:string,args:string[])=>({stdout:JSON.stringify(args.at(-1)?.includes("$drives=")?{drives:mocks.drives,paths:mocks.paths}:{version:"32.2.2",running:false})})}));
import {ObsDiscovery,inspectObs} from "../electron/obs-discovery";
/** 等待扫描异步完成而不是依赖固定睡眠。 */
async function finished(scan:ObsDiscovery){const deadline=Date.now()+5000;while(scan.state.running&&Date.now()<deadline)await new Promise(r=>setTimeout(r,10));expect(scan.state.running).toBe(false);}
it("finds candidates across C/D/E-style roots, deduplicates and marks incomplete programs",async()=>{const root=await mkdtemp(path.join(os.tmpdir(),"ln-scan-"));try{const exes:string[]=[];mocks.drives=[];for(const disk of ["C","D","E"]){const drive=path.join(root,disk);mocks.drives.push(drive);const program=path.join(drive,"直播工具","OBS");for(const f of ["bin/64bit/obs64.exe","bin/64bit/obs.dll","data/obs-studio/fixture","obs-plugins/64bit/obs-websocket.dll"]){await mkdir(path.dirname(path.join(program,f)),{recursive:true});await writeFile(path.join(program,f),"fixture");}exes.push(path.join(program,"bin/64bit/obs64.exe"));}mocks.paths=[exes[0],exes[0]];const incomplete=path.join(root,"D","incomplete","obs64.exe");await mkdir(path.dirname(incomplete));await writeFile(incomplete,"fixture");const resolvedAttached=await realpath(exes[1]);const scan=new ObsDiscovery();scan.start(true,[exes[1]]);await finished(scan);expect(scan.state.completedDrives).toHaveLength(3);expect(scan.state.results).toHaveLength(4);expect(scan.state.results.filter(c=>!c.error)).toHaveLength(3);expect(scan.state.results.find(c=>c.exe===resolvedAttached)?.attached).toBe(true);await expect(inspectObs(incomplete)).rejects.toThrow("不完整");const cancel=new ObsDiscovery();cancel.start(true,[]);cancel.cancel();await finished(cancel);expect(cancel.state.canceled).toBe(true);expect(cancel.state.completedDrives).toEqual([]);}finally{if(path.dirname(root)!==os.tmpdir()||!path.basename(root).startsWith("ln-scan-"))throw new Error("Unsafe cleanup");await rm(root,{recursive:true,force:true});}});
