/** 持久恢复测试使用真实文件/加密日志和合成 YouTube 端口，不操作 OBS 或真实频道。 */
import { beforeEach, afterEach, expect, it, vi } from "vitest";
import { mkdtemp, mkdir, writeFile, rm, readFile } from "node:fs/promises";
import os from "node:os"; import path from "node:path";
import { PublishingStore } from "@/core/publishing/storage";
import { PublishingRunner } from "@/core/publishing/runner";
import { scanPublishingAssets } from "@/core/publishing/assets";
import { seal } from "@/core/storage";
import { VideoApiError } from "@/core/youtube/video-api";
import { fixtureApi, fixtureJob } from "./publishing-fixtures";
import type { JobSpec, PublishingReport } from "@/shared/publishing";
import type { Service } from "@/core/service";
let root: string; let store: PublishingStore; let job: JobSpec; let now: number;
beforeEach(async () => { root = await mkdtemp(path.join(os.tmpdir(), "publishing-runner-")); vi.stubEnv("LIVEPILOT_INSTANCES", "main"); vi.stubEnv("LIVEPILOT_ENCRYPTION_KEY", "a".repeat(64)); vi.stubEnv("LIVEPILOT_DATA_ROOT", path.join(root, "data")); vi.stubEnv("LIVEPILOT_MEDIA_ROOT", root); await mkdir(path.join(root, "videos")); await mkdir(path.join(root, "music")); await writeFile(path.join(root, "videos", "movie.mp4"), Buffer.alloc(262150, 42)); store = new PublishingStore(path.join(root, "publisher")); job = fixtureJob((await scanPublishingAssets(root)).assets[0]); now = Date.parse("2026-10-01T00:00:00Z"); });
afterEach(async () => { vi.unstubAllEnvs(); vi.unstubAllGlobals(); if (path.dirname(root) !== os.tmpdir() || !path.basename(root).startsWith("publishing-runner-")) throw new Error("Unsafe cleanup"); await rm(root, { recursive: true, force: true }); });
/** 等待后台安全检查点，不让测试依赖真实上传耗时。 */
async function settle(runner: PublishingRunner) { for (let i = 0; i < 500 && runner.busy; i++) await new Promise(r => setTimeout(r, 5)); expect(runner.busy).toBe(false); }
/** 构造断电前的加密检查点，恢复必须读取而非重放 insert。 */
async function checkpoint(state: PublishingReport["state"], extra: Record<string, unknown> = {}) { await store.write("entries.enc", seal([{ spec: job, report: { id: job.id, revision: 1, sequence: 1, state, offset: 0, total: job.asset.size, updatedAt: now, metadata: { title: "movie", description: "Description" } }, playlistsDone: [], failures: 0, ...extra }])); }
it("uploads with no OBS using regular bandwidth, persists private session, then finalizes without SMTP", async () => {
  const { api, videos } = fixtureApi(); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply(job); await runner.tick(); await settle(runner);
  expect(api.begin).toHaveBeenCalledOnce(); expect(api.chunk).toHaveBeenCalledTimes(2); expect(api.chunk.mock.calls[0][5]).toBe(20); expect((await runner.reports())[0]).toMatchObject({ state: "processing", videoId: "video_one", offset: job.asset.size }); expect(await readFile(path.join(store.dir, "entries.enc"), "utf8")).not.toContain("upload_id");
  videos.get("video_one")!.processingDetails!.processingStatus = "succeeded"; now += 60001; await runner.tick(); await runner.tick(); await settle(runner); expect((await runner.reports())[0].state).toBe("completed"); expect(api.begin).toHaveBeenCalledOnce(); await runner.stop();
});
it("uses machine-level configured live bandwidth only for an explicit live signal", async () => { const { api } = fixtureApi(); job.policy.concurrency = 2; const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api, live: () => true }); await runner.apply(job); await runner.tick(); await settle(runner); expect(api.chunk.mock.calls[0][5]).toBe(2.5); await runner.stop(); });
it("probes persisted session after restart and trusts server offset", async () => { const { api } = fixtureApi(); await checkpoint("uploading", { session: "synthetic-session" }); api.probe.mockResolvedValue({ offset: 262144 }); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); await settle(runner); expect(api.begin).not.toHaveBeenCalled(); expect(api.chunk.mock.calls[0][2]).toBe(262144); await runner.stop(); });
it("waits for the original session result when all bytes are accepted without a video ID", async () => {
  const { api, videos } = fixtureApi(); await checkpoint("uploading", { session: "old", finalChunkPossible: true });
  api.probe.mockResolvedValueOnce({ offset: job.asset.size }).mockResolvedValueOnce({ offset: job.asset.size, videoId: "video_one" } as never);
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api });
  await runner.tick(); await settle(runner); expect((await runner.reports())[0].state).toBe("retry_wait"); expect(api.chunk).not.toHaveBeenCalled(); expect(api.begin).not.toHaveBeenCalled();
  videos.set("video_one", { id: "video_one", snippet: { channelId: "channel_one" }, status: { privacyStatus: "private" }, processingDetails: { processingStatus: "processing" } });
  now += 30001; await runner.tick(); await settle(runner); expect((await runner.reports())[0]).toMatchObject({ state: "processing", videoId: "video_one" }); expect(api.probe).toHaveBeenCalledTimes(2); expect(api.chunk).not.toHaveBeenCalled(); expect(api.begin).not.toHaveBeenCalled(); await runner.stop();
});
it.each([{ matches: [] as string[] }, { matches: ["v1", "v2"] }])("never begins a second upload when last chunk is uncertain (%j)", async ({ matches }) => { const { api } = fixtureApi(); await checkpoint("uploading", { session: "old", finalChunkPossible: true }); api.probe.mockResolvedValue({ offset: 0, expired: true } as never); api.recover.mockResolvedValue(matches); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); await settle(runner); expect(api.begin).not.toHaveBeenCalled(); expect(api.chunk).not.toHaveBeenCalled(); expect((await runner.reports())[0].state).toBe("needs_attention"); await runner.stop(); });
it("recovers exactly one marker match without sending video bytes again", async () => { const { api } = fixtureApi(); await checkpoint("uploading", { session: "old", finalChunkPossible: true }); api.probe.mockResolvedValue({ offset: 0, expired: true } as never); api.recover.mockResolvedValue(["v1"]); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); await settle(runner); expect((await runner.reports())[0]).toMatchObject({ state: "processing", videoId: "v1" }); expect(api.begin).not.toHaveBeenCalled(); expect(api.chunk).not.toHaveBeenCalled(); await runner.stop(); });
it("does not upload changed files or duplicate incoming revisions", async () => { const { api } = fixtureApi(); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await Promise.all([runner.apply(job), runner.apply(job)]); await expect(runner.apply({ ...job, overrides: { title: "Different" } })).rejects.toMatchObject({ code: "REQUEST" }); await writeFile(path.join(root, "videos", job.asset.filename), "changed"); await runner.tick(); await settle(runner); expect(api.begin).not.toHaveBeenCalled(); expect((await runner.reports())[0].state).toBe("needs_attention"); await runner.stop(); });
it("batches status by channel, treats a missing ID as unknown and only observes real public", async () => { const { api, videos } = fixtureApi(); const second = fixtureJob(job.asset); await store.write("entries.enc", seal([job, second].map((spec, i) => ({ spec, report: { id: spec.id, revision: 1, sequence: 1, state: "scheduled", videoId: "v" + i, offset: spec.asset.size, total: spec.asset.size, updatedAt: now }, playlistsDone: [], failures: 0 })))); videos.set("v0", { id: "v0", snippet: { channelId: "channel_one" }, status: { privacyStatus: "public" } }); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); expect(api.list).toHaveBeenCalledExactlyOnceWith(["v0", "v1"]); const reports = await runner.reports(); expect(reports[0].state).toBe("published"); expect(reports[1]).toMatchObject({ state: "scheduled", message: expect.stringContaining("没有认定删除") }); await runner.stop(); });
it("resumes a paused schedule by observing it and confirms cancel only after remote succeeds", async () => { const { api, videos } = fixtureApi(); await checkpoint("scheduled", { report: { id: job.id, revision: 1, sequence: 1, state: "scheduled", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now } }); videos.set("v1", { id: "v1", snippet: { channelId: "channel_one" }, status: { privacyStatus: "public" } }); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply({ ...job, revision: 2, desired: "pause" }); await runner.tick(); await settle(runner); expect((await runner.reports())[0].state).toBe("paused"); await runner.apply({ ...job, revision: 3 }); await runner.tick(); expect((await runner.reports())[0].state).toBe("published"); expect(api.finalize).not.toHaveBeenCalled(); api.unschedule.mockRejectedValue(new VideoApiError("ALREADY_PUBLIC", "Already public")); await runner.apply({ ...job, revision: 4, desired: "cancel" }); await runner.tick(); await settle(runner); expect((await runner.reports())[0].state).toBe("needs_attention"); await runner.tick(); expect(api.unschedule).toHaveBeenCalledOnce(); await runner.stop(); });
it("keeps reports until precise acknowledgement and preserves newer progress", async () => { const { api } = fixtureApi(); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply(job); await runner.acknowledge([{ id: job.id, sequence: 1 }]); expect(await runner.reports()).toEqual([]); await runner.apply({ ...job, revision: 2, desired: "pause" }); await runner.acknowledge([{ id: job.id, sequence: 1 }]); expect(await runner.reports()).toHaveLength(1); await runner.stop(); });
it("clears expired API data and prohibits a replacement upload", async () => { const { api } = fixtureApi(); await checkpoint("scheduled", { report: { id: job.id, revision: 1, sequence: 1, state: "scheduled", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, remoteCheckedAt: now - 31 * 86400_000 } }); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); expect((await runner.reports())[0]).toMatchObject({ state: "needs_attention", videoId: undefined }); await runner.apply({ ...job, revision: 2 }); await runner.tick(); await settle(runner); expect(api.begin).not.toHaveBeenCalled(); await runner.stop(); });
it("recovers a lost schedule response without shifting its time or finalizing twice", async () => { const { api, videos } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-09-01T00:00:00Z"; await checkpoint("finalizing", { report: { id: job.id, revision: 1, sequence: 1, state: "finalizing", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, metadata: { title: "movie", description: "Description" } } }); videos.set("v1", { id: "v1", snippet: { channelId: "channel_one" }, status: { privacyStatus: "private" } }); const finalize = api.finalize.getMockImplementation()!; api.finalize.mockImplementationOnce(async (...args) => { await finalize(...args); const remote = videos.get("v1")!; remote.status!.publishAt = remote.status!.publishAt!.replace(".000Z", "Z"); throw new VideoApiError("VIDEO_NETWORK", "lost response", true); }); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); await settle(runner); expect((await runner.reports())[0].state).toBe("retry_wait"); now += 60001; await runner.tick(); await settle(runner); expect((await runner.reports())[0]).toMatchObject({ state: "scheduled", effectivePublishAt: "2026-10-01T00:10:00.000Z" }); expect(api.finalize).toHaveBeenCalledOnce(); now += 3600000; await runner.tick(); expect((await runner.reports())[0].state).toBe("scheduled"); videos.get("v1")!.status!.privacyStatus = "public"; now += 60001; await runner.tick(); expect((await runner.reports())[0].state).toBe("published"); await runner.stop(); });
it("retries only the failed playlist step and never reuploads a completed video", async () => { const { api, videos } = fixtureApi(); job.profile.playlistIds = ["PLfirst", "PLsecond"]; await checkpoint("finalizing", { report: { id: job.id, revision: 1, sequence: 1, state: "finalizing", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, metadata: { title: "movie", description: "Description" } } }); videos.set("v1", { id: "v1", snippet: { channelId: "channel_one" }, status: { privacyStatus: "private" } }); api.playlist.mockResolvedValueOnce(undefined).mockRejectedValueOnce(new VideoApiError("VIDEO_NETWORK", "lost insert", true)); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); await settle(runner); now += 60001; await runner.tick(); await settle(runner); expect(api.playlist.mock.calls).toEqual([["v1", "PLfirst"], ["v1", "PLsecond"], ["v1", "PLsecond"]]); expect(api.begin).not.toHaveBeenCalled(); expect((await runner.reports())[0].state).toBe("completed"); await runner.stop(); });
it("blocks upload when the instance authorization channel changes", async () => { const { api } = fixtureApi(); const service = { auth: { tokens: async () => ({ channelId: "other_channel" }) } } as unknown as Service; const runner = new PublishingRunner(new Map([["main", service]]), { store, now: () => now, api: () => api }); await runner.apply(job); await runner.tick(); await settle(runner); expect(api.begin).not.toHaveBeenCalled(); expect((await runner.reports())[0].state).toBe("needs_attention"); await runner.stop(); });
it("does not turn an unknown last-chunk result into a cancelled job that can be requeued", async () => { const { api } = fixtureApi(); await checkpoint("uploading", { session: "old", finalChunkPossible: true }); api.probe.mockResolvedValue({ offset: 0, expired: true } as never); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply({ ...job, revision: 2, desired: "cancel" }); await runner.tick(); await settle(runner); expect((await runner.reports())[0].state).toBe("needs_attention"); expect(api.begin).not.toHaveBeenCalled(); expect(api.unschedule).not.toHaveBeenCalled(); await runner.stop(); });
