/** 持久恢复测试使用真实文件/加密日志和合成 YouTube 端口，不操作 OBS 或真实频道。 */
import { beforeEach, afterEach, expect, it, vi } from "vitest";
import { mkdtemp, mkdir, writeFile, rm, readFile } from "node:fs/promises";
import os from "node:os"; import path from "node:path";
import { PublishingStore } from "@/core/publishing/storage";
import { PublishingRunner } from "@/core/publishing/runner";
import { scanPublishingAssets } from "@/core/publishing/assets";
import { seal, unseal } from "@/core/storage";
import { VideoApiError } from "@/core/youtube/video-api";
import { fixtureApi, fixtureJob } from "./publishing-fixtures";
import type { JobSpec, PublishingReport } from "@/shared/publishing";
import type { Service } from "@/core/service";
let root: string; let store: PublishingStore; let job: JobSpec; let now: number;
beforeEach(async () => { root = await mkdtemp(path.join(os.tmpdir(), "publishing-runner-")); vi.stubEnv("LIVEPILOT_INSTANCES", "main"); vi.stubEnv("LIVEPILOT_ENCRYPTION_KEY", "a".repeat(64)); vi.stubEnv("LIVEPILOT_DATA_ROOT", path.join(root, "data")); vi.stubEnv("LIVEPILOT_MEDIA_ROOT", root); await mkdir(path.join(root, "videos")); await mkdir(path.join(root, "music")); await writeFile(path.join(root, "videos", "movie.mp4"), Buffer.alloc(262150, 42)); store = new PublishingStore(path.join(root, "publisher")); job = fixtureJob((await scanPublishingAssets(root)).assets[0]); now = Date.parse("2026-10-01T00:00:00Z"); });
afterEach(async () => { vi.unstubAllEnvs(); vi.unstubAllGlobals(); if (path.dirname(root) !== os.tmpdir() || !path.basename(root).startsWith("publishing-runner-")) throw new Error("Unsafe cleanup"); await rm(root, { recursive: true, force: true }); });
/** 等待后台安全检查点，不让测试依赖真实上传耗时。 */
async function settle(runner: PublishingRunner) { for (let i = 0; i < 500 && runner.busy; i++) await new Promise(r => setTimeout(r, 5)); expect(runner.busy).toBe(false); }
/** 构造断电前的加密检查点，恢复必须读取而非重放 insert。 */
async function checkpoint(state: PublishingReport["state"], extra: Record<string, unknown> = {}) { await store.write("entries.enc", seal([{ spec: job, report: { id: job.id, revision: 1, sequence: 1, state, offset: 0, total: job.asset.size, updatedAt: now, metadata: { title: "movie", description: "Description" } }, playlistsDone: [], failures: 0, ...extra }])); }
it("uploads with no OBS using regular bandwidth, persists private session, then finalizes without SMTP", async () => {
  const { api, videos } = fixtureApi(); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply(job); await runner.tick(); await settle(runner);
  expect(api.begin).toHaveBeenCalledOnce(); expect(api.chunk).toHaveBeenCalledTimes(2); expect(api.chunk.mock.calls[0][5]).toBe(20); expect((await runner.reports())[0]).toMatchObject({ state: "processing", videoId: "video_one", offset: job.asset.size }); expect(await readFile(path.join(store.dir, "entries.enc"), "utf8")).not.toContain("upload_id");
  videos.get("video_one")!.processingDetails!.processingStatus = "succeeded"; now += 60001; await runner.tick(); await runner.tick(); await settle(runner); expect((await runner.reports())[0].state).toBe("completed"); expect(api.begin).toHaveBeenCalledOnce(); await runner.stop();
});
it("uses machine-level configured live bandwidth only for an explicit live signal", async () => { const { api } = fixtureApi(); job.policy.concurrency = 2; const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api, live: () => true }); await runner.apply(job); await runner.tick(); await settle(runner); expect(api.chunk.mock.calls[0][5]).toBe(2.5); await runner.stop(); });
it("probes persisted session after restart and trusts server offset", async () => { const { api } = fixtureApi(); await checkpoint("uploading", { session: "synthetic-session" }); api.probe.mockResolvedValue({ offset: 262144 }); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); await settle(runner); expect(api.begin).not.toHaveBeenCalled(); expect(api.chunk.mock.calls[0][2]).toBe(262144); await runner.stop(); });
it("waits for the original session result when all bytes are accepted without a video ID", async () => {
  const { api, videos } = fixtureApi(); await checkpoint("uploading", { session: "old", finalChunkPossible: true });
  api.probe.mockResolvedValueOnce({ offset: job.asset.size }).mockResolvedValueOnce({ offset: job.asset.size, videoId: "video_one" } as never);
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api });
  await runner.tick(); await settle(runner); expect((await runner.reports())[0].state).toBe("retry_wait"); expect(api.chunk).not.toHaveBeenCalled(); expect(api.begin).not.toHaveBeenCalled();
  videos.set("video_one", { id: "video_one", snippet: { channelId: "channel_one" }, status: { privacyStatus: "private" }, processingDetails: { processingStatus: "processing" } });
  now += 30001; await runner.tick(); await settle(runner); expect((await runner.reports())[0]).toMatchObject({ state: "processing", videoId: "video_one" }); expect(api.probe).toHaveBeenCalledTimes(2); expect(api.chunk).not.toHaveBeenCalled(); expect(api.begin).not.toHaveBeenCalled(); await runner.stop();
});
it.each([{ matches: [] as string[] }, { matches: ["v1", "v2"] }])("never begins a second upload when last chunk is uncertain (%j)", async ({ matches }) => { const { api } = fixtureApi(); await checkpoint("uploading", { session: "old", finalChunkPossible: true }); api.probe.mockResolvedValue({ offset: 0, expired: true } as never); api.recover.mockResolvedValue(matches); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); await settle(runner); expect(api.begin).not.toHaveBeenCalled(); expect(api.chunk).not.toHaveBeenCalled(); expect((await runner.reports())[0].state).toBe("needs_attention"); await runner.stop(); });
it("recovers exactly one marker match without sending video bytes again", async () => { const { api } = fixtureApi(); await checkpoint("uploading", { session: "old", finalChunkPossible: true }); api.probe.mockResolvedValue({ offset: 0, expired: true } as never); api.recover.mockResolvedValue(["v1"]); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); await settle(runner); expect((await runner.reports())[0]).toMatchObject({ state: "processing", videoId: "v1" }); expect(api.begin).not.toHaveBeenCalled(); expect(api.chunk).not.toHaveBeenCalled(); await runner.stop(); });
it("does not upload changed files or duplicate incoming revisions", async () => { const { api } = fixtureApi(); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await Promise.all([runner.apply(job), runner.apply(job)]); await expect(runner.apply({ ...job, overrides: { title: "Different" } })).rejects.toMatchObject({ code: "REQUEST" }); await writeFile(path.join(root, "videos", job.asset.filename), "changed"); await runner.tick(); await settle(runner); expect(api.begin).not.toHaveBeenCalled(); expect((await runner.reports())[0].state).toBe("needs_attention"); await runner.stop(); });
it("batches status by channel, treats a missing ID as unknown and only observes real public", async () => { const { api, videos } = fixtureApi(); const second = fixtureJob(job.asset); await store.write("entries.enc", seal([job, second].map((spec, i) => ({ spec, report: { id: spec.id, revision: 1, sequence: 1, state: "scheduled", videoId: "v" + i, offset: spec.asset.size, total: spec.asset.size, updatedAt: now }, playlistsDone: [], failures: 0 })))); videos.set("v0", { id: "v0", snippet: { channelId: "channel_one" }, status: { privacyStatus: "public" } }); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); expect(api.list).toHaveBeenCalledExactlyOnceWith(["v0", "v1"]); const reports = await runner.reports(); expect(reports[0].state).toBe("published"); expect(reports[1]).toMatchObject({ state: "scheduled", message: expect.stringContaining("没有认定删除") }); await runner.stop(); });
it("resumes a paused schedule by observing it and rejects cancellation of known publication", async () => { const { api, videos } = fixtureApi(); await checkpoint("scheduled", { report: { id: job.id, revision: 1, sequence: 1, state: "scheduled", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now } }); videos.set("v1", { id: "v1", snippet: { channelId: "channel_one" }, status: { privacyStatus: "public" } }); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply({ ...job, revision: 2, desired: "pause" }); await runner.tick(); await settle(runner); expect((await runner.reports())[0].state).toBe("paused"); await runner.apply({ ...job, revision: 3 }); await runner.tick(); expect((await runner.reports())[0].state).toBe("published"); expect(api.finalize).not.toHaveBeenCalled(); api.unschedule.mockRejectedValue(new VideoApiError("ALREADY_PUBLIC", "Already public")); await runner.apply({ ...job, revision: 4, desired: "cancel" }); await runner.tick(); await settle(runner); expect((await runner.reports())[0]).toMatchObject({ revision: 4, state: "published", observedPrivacy: "public", message: expect.stringContaining("取消未应用") }); await runner.tick(); expect(api.unschedule).not.toHaveBeenCalled(); await runner.stop(); });
it("keeps reports until precise acknowledgement and preserves newer progress", async () => { const { api } = fixtureApi(); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply(job); await runner.acknowledge([{ id: job.id, sequence: 1 }]); expect(await runner.reports()).toEqual([]); await runner.apply({ ...job, revision: 2, desired: "pause" }); await runner.acknowledge([{ id: job.id, sequence: 1 }]); expect(await runner.reports()).toHaveLength(1); await runner.stop(); });
it("clears expired API data and prohibits a replacement upload", async () => { const { api } = fixtureApi(); await checkpoint("scheduled", { report: { id: job.id, revision: 1, sequence: 1, state: "scheduled", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, remoteCheckedAt: now - 31 * 86400_000 } }); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); expect((await runner.reports())[0]).toMatchObject({ state: "needs_attention", videoId: undefined }); await runner.apply({ ...job, revision: 2 }); await runner.tick(); await settle(runner); expect(api.begin).not.toHaveBeenCalled(); await runner.stop(); });
it.each(["published", "completed"] as const)("preserves the durable %s result when API observations expire across restarts", async state => {
  const { api } = fixtureApi(); await checkpoint(state, { session: "finished-session", report: { id: job.id, revision: 1, sequence: 1, state, videoId: "v1", observedPrivacy: state === "published" ? "public" : "private", metadata: { title: "old API title", description: "old API description" }, offset: job.asset.size, total: job.asset.size, updatedAt: now, remoteCheckedAt: now - 31 * 86400_000 } });
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); expect((await runner.reports())[0]).toMatchObject({ state, videoId: undefined, observedPrivacy: undefined, metadata: undefined }); await runner.stop();
  const restored = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await restored.tick(); expect((await restored.reports())[0].state).toBe(state); expect(api.begin).not.toHaveBeenCalled(); expect(api.list).not.toHaveBeenCalled(); await restored.stop();
});
it("does not merge equal-channel lookups from separate publishing authorization contexts", async () => {
  const a = fixtureApi(); const b = fixtureApi(); job.profile.accountId = "11111111-1111-4111-8111-111111111111"; const other = fixtureJob(job.asset); other.profile.accountId = "22222222-2222-4222-8222-222222222222";
  await store.write("entries.enc", seal([job, other].map((spec, index) => ({ spec, report: { id: spec.id, revision: 1, sequence: 1, state: "scheduled", videoId: "v" + index, offset: spec.asset.size, total: spec.asset.size, updatedAt: now }, playlistsDone: [], failures: 0 }))));
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: spec => spec.profile.accountId === job.profile.accountId ? a.api : b.api }); await runner.tick(); expect(a.api.list).toHaveBeenCalledExactlyOnceWith(["v0"]); expect(b.api.list).toHaveBeenCalledExactlyOnceWith(["v1"]); await runner.stop();
});
it("purges only the selected account or legacy context and keeps another account on the same host", async () => {
  const account = fixtureJob(job.asset); account.profile.accountId = "11111111-1111-4111-8111-111111111111"; const other = fixtureJob(job.asset); other.profile.accountId = "22222222-2222-4222-8222-222222222222";
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => fixtureApi().api }); for (const spec of [job, account, other]) await runner.apply(spec);
  await runner.purge("main", account.profile.accountId); expect((await runner.reports()).map(value => value.id)).toEqual([job.id, other.id]);
  await runner.purge("main"); expect((await runner.reports()).map(value => value.id)).toEqual([other.id]); await runner.stop();
});
it("recovers a lost schedule response without shifting its time or finalizing twice", async () => { const { api, videos } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-09-01T00:00:00Z"; await checkpoint("finalizing", { report: { id: job.id, revision: 1, sequence: 1, state: "finalizing", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, metadata: { title: "movie", description: "Description" } } }); videos.set("v1", { id: "v1", snippet: { channelId: "channel_one" }, status: { privacyStatus: "private" } }); const finalize = api.finalize.getMockImplementation()!; api.finalize.mockImplementationOnce(async (...args) => { await finalize(...args); const remote = videos.get("v1")!; remote.status!.publishAt = remote.status!.publishAt!.replace(".000Z", "Z"); throw new VideoApiError("VIDEO_NETWORK", "lost response", true); }); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); await settle(runner); expect((await runner.reports())[0].state).toBe("retry_wait"); now += 60001; await runner.tick(); await settle(runner); expect((await runner.reports())[0]).toMatchObject({ state: "scheduled", effectivePublishAt: "2026-10-01T00:10:00.000Z" }); expect(api.finalize).toHaveBeenCalledOnce(); now += 3600000; await runner.tick(); expect((await runner.reports())[0].state).toBe("scheduled"); videos.get("v1")!.status!.privacyStatus = "public"; now += 60001; await runner.tick(); expect((await runner.reports())[0].state).toBe("published"); await runner.stop(); });
it("retries only the failed playlist step and never reuploads a completed video", async () => { const { api, videos } = fixtureApi(); job.profile.playlistIds = ["PLfirst", "PLsecond"]; await checkpoint("finalizing", { report: { id: job.id, revision: 1, sequence: 1, state: "finalizing", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, metadata: { title: "movie", description: "Description" } } }); videos.set("v1", { id: "v1", snippet: { channelId: "channel_one" }, status: { privacyStatus: "private" } }); api.playlist.mockResolvedValueOnce(undefined).mockRejectedValueOnce(new VideoApiError("VIDEO_NETWORK", "lost insert", true)); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); await settle(runner); now += 60001; await runner.tick(); await settle(runner); expect(api.playlist.mock.calls).toEqual([["v1", "PLfirst"], ["v1", "PLsecond"], ["v1", "PLsecond"]]); expect(api.begin).not.toHaveBeenCalled(); expect((await runner.reports())[0].state).toBe("completed"); await runner.stop(); });
it("blocks upload when the instance authorization channel changes", async () => { const { api } = fixtureApi(); const service = { auth: { tokens: async () => ({ channelId: "other_channel" }) } } as unknown as Service; const runner = new PublishingRunner(new Map([["main", service]]), { store, now: () => now, api: () => api }); await runner.apply(job); await runner.tick(); await settle(runner); expect(api.begin).not.toHaveBeenCalled(); expect((await runner.reports())[0].state).toBe("needs_attention"); await runner.stop(); });
it("does not turn an unknown last-chunk result into a cancelled job that can be requeued", async () => { const { api } = fixtureApi(); await checkpoint("uploading", { session: "old", finalChunkPossible: true }); api.probe.mockResolvedValue({ offset: 0, expired: true } as never); const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply({ ...job, revision: 2, desired: "cancel" }); await runner.tick(); await settle(runner); expect((await runner.reports())[0].state).toBe("needs_attention"); expect(api.begin).not.toHaveBeenCalled(); expect(api.unschedule).not.toHaveBeenCalled(); await runner.stop(); });
it.each([false, true])("applies a newer schedule after a delayed old finalization and restart without reuploading (lost=%s)", async lost => {
  const { api, videos } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-10-02T12:00:00Z";
  const copy = { title: "Persisted title", description: "Persisted copy" }; const finalUpload = { asset: job.asset, relativePath: "Working/001/output.mp4", sha256: "c".repeat(64) };
  await checkpoint("finalizing", { finalUpload, session: "original-session", sha256: finalUpload.sha256, finalChunkPossible: true, report: { id: job.id, revision: 1, sequence: 1, state: "finalizing", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, metadata: copy } });
  videos.set("v1", { id: "v1", snippet: { channelId: "channel_one" }, status: { privacyStatus: "private" } });
  let started!: () => void; let release!: () => void; const entered = new Promise<void>(resolve => { started = resolve; }); const gate = new Promise<void>(resolve => { release = resolve; });
  const finalize = api.finalize.getMockImplementation()!;
  /** Hold the old write open while the persisted new revision arrives; its late result cannot confirm the new intent. */
  api.finalize.mockImplementationOnce(async (...args) => { started(); await gate; await finalize(...args); if (lost) throw new VideoApiError("VIDEO_NETWORK", "Delayed response lost", true); });
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); await entered;
  const revised = { ...job, revision: 2, originalPublishAt: "2026-10-03T18:00:00Z" }; await runner.apply(revised); release(); await settle(runner);
  expect((await runner.reports())[0]).toMatchObject({ revision: 2, state: "finalizing", videoId: "v1", metadata: copy }); await runner.stop();
  const restored = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await restored.tick(); await settle(restored);
  expect((await restored.reports())[0]).toMatchObject({ revision: 2, state: "scheduled", videoId: "v1", metadata: copy, effectivePublishAt: "2026-10-03T18:00:00.000Z" });
  expect(api.finalize).toHaveBeenCalledTimes(2); expect(api.finalize.mock.calls[1]).toEqual(["v1", expect.objectContaining({ revision: 2 }), copy, "2026-10-03T18:00:00.000Z"]); expect(api.begin).not.toHaveBeenCalled(); expect(api.chunk).not.toHaveBeenCalled();
  const encrypted = await store.read<string>("entries.enc"); const entries = unseal<{ session: string; finalUpload: unknown; sha256: string }[]>(encrypted!); expect(entries[0]).toMatchObject({ session: "original-session", finalUpload, sha256: finalUpload.sha256 }); await restored.stop();
});
it("preserves a paused schedule revision until explicit resume, then changes only the original remote video", async () => {
  const { api, videos } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-10-02T12:00:00Z";
  const copy = { title: "Persisted title", description: "Persisted copy" }; await api.finalize("v1", job, copy, job.originalPublishAt); api.finalize.mockClear();
  await checkpoint("paused", { finalized: true, resumeState: "scheduled", report: { id: job.id, revision: 1, sequence: 1, state: "paused", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, effectivePublishAt: job.originalPublishAt, metadata: copy } });
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); const revised = { ...job, revision: 2, desired: "pause" as const, originalPublishAt: "2026-10-03T18:00:00Z" }; await runner.apply(revised); await runner.tick(); await settle(runner);
  expect((await runner.reports())[0]).toMatchObject({ revision: 2, state: "paused", effectivePublishAt: job.originalPublishAt }); expect(videos.get("v1")!.status!.publishAt).toBe(job.originalPublishAt); expect(api.finalize).not.toHaveBeenCalled();
  await runner.apply({ ...revised, revision: 3, desired: "run" }); await runner.tick(); await settle(runner); expect((await runner.reports())[0]).toMatchObject({ revision: 3, state: "scheduled", effectivePublishAt: "2026-10-03T18:00:00.000Z" }); expect(api.finalize).toHaveBeenCalledOnce(); expect(api.begin).not.toHaveBeenCalled(); await runner.stop();
});
it("reports a late schedule revision at the current revision when the Agent already observed publication", async () => {
  const { api } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-10-02T12:00:00Z";
  await checkpoint("published", { report: { id: job.id, revision: 1, sequence: 1, state: "published", observedPrivacy: "public", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, effectivePublishAt: job.originalPublishAt } });
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.acknowledge([{ id: job.id, sequence: 1 }]); await runner.apply({ ...job, revision: 2, originalPublishAt: "2026-10-03T18:00:00Z" }); await runner.tick();
  expect((await runner.reports())[0]).toMatchObject({ revision: 2, sequence: 2, state: "published", observedPrivacy: "public", effectivePublishAt: job.originalPublishAt, message: expect.stringContaining("改期未应用") }); expect(api.list).not.toHaveBeenCalled(); expect(api.finalize).not.toHaveBeenCalled(); expect(api.begin).not.toHaveBeenCalled(); await runner.stop();
});
it("waits for YouTube processing after a timing revision before finalizing the same video", async () => {
  const { api, videos } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-10-02T12:00:00Z";
  await checkpoint("processing", { report: { id: job.id, revision: 1, sequence: 1, state: "processing", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, metadata: { title: "Persisted title", description: "Persisted copy" } } });
  videos.set("v1", { id: "v1", snippet: { channelId: "channel_one" }, status: { privacyStatus: "private" }, processingDetails: { processingStatus: "processing" } });
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply({ ...job, revision: 2, originalPublishAt: "2026-10-03T18:00:00Z" }); await runner.tick(); expect((await runner.reports())[0]).toMatchObject({ revision: 2, state: "processing" }); expect(api.finalize).not.toHaveBeenCalled();
  videos.get("v1")!.processingDetails!.processingStatus = "succeeded"; now += 60001; await runner.tick(); await runner.tick(); await settle(runner); expect((await runner.reports())[0]).toMatchObject({ revision: 2, state: "scheduled", effectivePublishAt: "2026-10-03T18:00:00.000Z" }); expect(api.finalize).toHaveBeenCalledOnce(); expect(api.begin).not.toHaveBeenCalled(); await runner.stop();
});
it.each(["ALREADY_PUBLIC", "VIDEO_CHANGED"])("reconciles publication during the conditional schedule write (%s)", async code => {
  const { api, videos } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-10-02T12:00:00Z";
  const copy = { title: "Persisted title", description: "Persisted copy" }; await api.finalize("v1", job, copy, job.originalPublishAt); api.finalize.mockClear(); await checkpoint("scheduled", { finalized: true, report: { id: job.id, revision: 1, sequence: 1, state: "scheduled", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, effectivePublishAt: job.originalPublishAt, metadata: copy } });
  /** Simulate publication between the outer read and conditional API update, with no accepted write. */
  api.finalize.mockImplementationOnce(async () => { videos.get("v1")!.status!.privacyStatus = "public"; delete videos.get("v1")!.status!.publishAt; throw new VideoApiError(code, "Publication won the race"); });
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply({ ...job, revision: 2, originalPublishAt: "2026-10-03T18:00:00Z" }); await runner.tick(); await settle(runner);
  expect((await runner.reports())[0]).toMatchObject({ revision: 2, state: "published", observedPrivacy: "public", effectivePublishAt: job.originalPublishAt, message: expect.stringContaining("改期未应用") }); expect(api.finalize).toHaveBeenCalledOnce(); expect(api.begin).not.toHaveBeenCalled(); expect(api.chunk).not.toHaveBeenCalled(); await runner.stop();
});
it("does not turn a newer timing revision into a retry of an unknown last-chunk result", async () => {
  const { api } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-10-02T12:00:00Z"; await checkpoint("needs_attention", { session: "original-session", finalChunkPossible: true });
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply({ ...job, revision: 2, originalPublishAt: "2026-10-03T18:00:00Z" }); await runner.tick(); expect((await runner.reports())[0]).toMatchObject({ revision: 2, state: "needs_attention", message: expect.stringContaining("改期未应用") }); expect(api.probe).not.toHaveBeenCalled(); expect(api.begin).not.toHaveBeenCalled(); expect(api.chunk).not.toHaveBeenCalled(); await runner.stop();
});
it("clears an unverified legacy finalization marker and allows explicit schedule recovery", async () => {
  const { api, videos } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-10-03T18:00:00Z";
  const copy = { title: "Persisted title", description: "Persisted copy" }; await checkpoint("finalizing", { finalized: true, report: { id: job.id, revision: 1, sequence: 1, state: "finalizing", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, effectivePublishAt: job.originalPublishAt, metadata: copy } });
  videos.set("v1", { id: "v1", snippet: { channelId: "channel_one", title: "Old copy" }, status: { privacyStatus: "private", publishAt: "2026-10-02T12:00:00Z" } });
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); await settle(runner); expect((await runner.reports())[0].state).toBe("needs_attention"); expect(api.finalize).not.toHaveBeenCalled();
  const saved = await store.read<string>("entries.enc"); expect(unseal<{ finalized: boolean }[]>(saved!)[0].finalized).toBe(false);
  await runner.apply({ ...job, revision: 2 }); await runner.tick(); await settle(runner); expect((await runner.reports())[0]).toMatchObject({ revision: 2, state: "scheduled", effectivePublishAt: "2026-10-03T18:00:00.000Z" }); expect(api.finalize).toHaveBeenCalledOnce(); expect(api.begin).not.toHaveBeenCalled(); await runner.stop();
});
it("recovers a missing post-write verification without sending the schedule update twice", async () => {
  const { api, videos } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-10-03T18:00:00Z";
  await checkpoint("finalizing", { report: { id: job.id, revision: 1, sequence: 1, state: "finalizing", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, metadata: { title: "Persisted title", description: "Persisted copy" } } });
  videos.set("v1", { id: "v1", snippet: { channelId: "channel_one" }, status: { privacyStatus: "private" } }); const list = api.list.getMockImplementation()!; api.list.mockImplementationOnce(list).mockResolvedValueOnce([]);
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.tick(); await settle(runner); expect((await runner.reports())[0].state).toBe("retry_wait"); const saved = await store.read<string>("entries.enc"); expect(unseal<{ finalized?: boolean }[]>(saved!)[0].finalized).not.toBe(true);
  now += 30001; await runner.tick(); await settle(runner); expect((await runner.reports())[0]).toMatchObject({ state: "scheduled", effectivePublishAt: "2026-10-03T18:00:00.000Z" }); expect(api.finalize).toHaveBeenCalledOnce(); expect(api.begin).not.toHaveBeenCalled(); await runner.stop();
});
it.each(["ALREADY_PUBLIC", "VIDEO_CHANGED"])("records actual publication when cancellation loses the remote race (%s)", async code => {
  const { api, videos } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-10-02T12:00:00Z";
  await checkpoint("scheduled", { finalized: true, report: { id: job.id, revision: 1, sequence: 1, state: "scheduled", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, effectivePublishAt: job.originalPublishAt } });
  videos.set("v1", { id: "v1", snippet: { channelId: "channel_one" }, status: { privacyStatus: "private", publishAt: job.originalPublishAt } });
  /** The remote video becomes public before cancellation can be confirmed; no second write is allowed. */
  api.unschedule.mockImplementationOnce(async () => { videos.get("v1")!.status = { privacyStatus: "public" }; throw new VideoApiError(code, "Publication won the cancellation race"); });
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply({ ...job, revision: 2, desired: "cancel" }); await runner.tick(); await settle(runner);
  expect((await runner.reports())[0]).toMatchObject({ revision: 2, state: "published", videoId: "v1", observedPrivacy: "public", effectivePublishAt: job.originalPublishAt, message: expect.stringContaining("取消未应用") }); expect(api.unschedule).toHaveBeenCalledOnce(); expect(api.finalize).not.toHaveBeenCalled(); expect(api.begin).not.toHaveBeenCalled(); await runner.stop();
});
it.each([false, true])("reconciles a delayed cancellation before applying a newer schedule on the same video (lost=%s)", async lost => {
  const { api, videos } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-10-02T12:00:00Z";
  const copy = { title: "Persisted title", description: "Persisted copy" }; await api.finalize("v1", job, copy, job.originalPublishAt); api.finalize.mockClear();
  await checkpoint("scheduled", { finalized: true, session: "original-session", finalChunkPossible: true, report: { id: job.id, revision: 1, sequence: 1, state: "scheduled", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, metadata: copy, effectivePublishAt: job.originalPublishAt } });
  let started!: () => void; let release!: () => void; const entered = new Promise<void>(resolve => { started = resolve; }); const gate = new Promise<void>(resolve => { release = resolve; });
  /** The old cancellation takes effect while a new time has already been persisted; even a lost response belongs to the old intent. */
  api.unschedule.mockImplementationOnce(async () => { started(); await gate; delete videos.get("v1")!.status!.publishAt; if (lost) throw new VideoApiError("VIDEO_NETWORK", "Cancellation response lost", true); });
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply({ ...job, revision: 2, desired: "cancel" }); await runner.tick(); await entered;
  await runner.apply({ ...job, revision: 3, desired: "run", originalPublishAt: "2026-10-03T18:00:00Z" }); release(); await settle(runner);
  expect((await runner.reports())[0]).toMatchObject({ revision: 3, state: "finalizing", videoId: "v1", metadata: copy }); await runner.stop();
  const restored = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await restored.tick(); await settle(restored);
  expect((await restored.reports())[0]).toMatchObject({ revision: 3, state: "scheduled", videoId: "v1", effectivePublishAt: "2026-10-03T18:00:00.000Z", metadata: copy }); expect(api.finalize).toHaveBeenCalledOnce(); expect(api.begin).not.toHaveBeenCalled(); expect(api.chunk).not.toHaveBeenCalled(); await restored.stop();
});
it("keeps a newer pause after an old cancellation response and resumes the original video safely", async () => {
  const { api, videos } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-10-02T12:00:00Z";
  const copy = { title: "Persisted title", description: "Persisted copy" }; await api.finalize("v1", job, copy, job.originalPublishAt); api.finalize.mockClear();
  await checkpoint("scheduled", { finalized: true, report: { id: job.id, revision: 1, sequence: 1, state: "scheduled", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, metadata: copy, effectivePublishAt: job.originalPublishAt } });
  let started!: () => void; let release!: () => void; const entered = new Promise<void>(resolve => { started = resolve; }); const gate = new Promise<void>(resolve => { release = resolve; });
  /** Pause arrives after the old remote request started; its eventual success must not report cancellation for the pause revision. */
  api.unschedule.mockImplementationOnce(async () => { started(); await gate; delete videos.get("v1")!.status!.publishAt; });
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply({ ...job, revision: 2, desired: "cancel" }); await runner.tick(); await entered; await runner.apply({ ...job, revision: 3, desired: "pause" }); release(); await settle(runner);
  expect((await runner.reports())[0]).toMatchObject({ revision: 3, state: "paused", videoId: "v1" }); expect(api.finalize).not.toHaveBeenCalled();
  await runner.apply({ ...job, revision: 4, desired: "run" }); await runner.tick(); await settle(runner); expect((await runner.reports())[0]).toMatchObject({ revision: 4, state: "scheduled", videoId: "v1", effectivePublishAt: "2026-10-02T12:00:00.000Z" }); expect(api.finalize).toHaveBeenCalledOnce(); expect(api.begin).not.toHaveBeenCalled(); await runner.stop();
});
it("does not publish a stale cancellation error as a newer resume rejection when readback is unavailable", async () => {
  const { api } = fixtureApi(); job.profile.privacy = "public"; job.profile.scheduled = true; job.originalPublishAt = "2026-10-02T12:00:00Z";
  await checkpoint("scheduled", { finalized: true, report: { id: job.id, revision: 1, sequence: 1, state: "scheduled", videoId: "v1", offset: job.asset.size, total: job.asset.size, updatedAt: now, effectivePublishAt: job.originalPublishAt } });
  let started!: () => void; let release!: () => void; const entered = new Promise<void>(resolve => { started = resolve; }); const gate = new Promise<void>(resolve => { release = resolve; });
  api.unschedule.mockImplementationOnce(async () => { started(); await gate; throw new VideoApiError("VIDEO_CHANGED", "Old cancellation lost the race"); }); api.list.mockRejectedValue(new VideoApiError("VIDEO_NETWORK", "Readback unavailable", true));
  const runner = new PublishingRunner(new Map(), { store, now: () => now, api: () => api }); await runner.apply({ ...job, revision: 2, desired: "cancel" }); await runner.tick(); await entered; await runner.apply({ ...job, revision: 3, desired: "run" }); release(); await settle(runner);
  expect((await runner.reports())[0]).toMatchObject({ revision: 3, state: "retry_wait", videoId: "v1", nextAttemptAt: now + 30_000 }); expect(api.begin).not.toHaveBeenCalled(); expect(api.finalize).not.toHaveBeenCalled(); await runner.stop();
});
