/** Resumable HTTP 合同使用合成授权及模拟响应，验证流式边界和字段保留。 */
import { afterEach, expect, it, vi } from "vitest";
import { VideoApi, validateSession } from "@/core/youtube/video-api";
import type { YouTubeAuth } from "@/core/youtube/auth";
import { fixtureJob } from "./publishing-fixtures";
const uri = "https://www.googleapis.com/upload/youtube/v3/videos?upload_id=synthetic";
/** API 依赖只返回虚构频道和 Token，网络必须在每个测试中模拟。 */
function client() { return new VideoApi({ access: async () => ({ accessToken: "synthetic", channelId: "channel_one" }), tokens: async () => ({ channelId: "channel_one" }) } as unknown as YouTubeAuth, vi.fn(async () => {})); }
afterEach(() => vi.unstubAllGlobals());
it.each(["https://evil.invalid/upload/youtube/v3/videos", "http://www.googleapis.com/upload/youtube/v3/videos", "https://user@www.googleapis.com/upload/youtube/v3/videos", "https://www.googleapis.com:123/upload/youtube/v3/videos"])("does not send authorization to an unsafe session (%s)", value => { expect(() => validateSession(value)).toThrow(); });
it("inserts private without publishAt and persists a validated Location", async () => { const fetcher = vi.fn<typeof fetch>(async () => new Response(null, { status: 200, headers: { location: uri } })); vi.stubGlobal("fetch", fetcher); const job = fixtureJob(); job.profile.privacy = "public"; job.profile.scheduled = true; const api = client(); expect(await api.begin(job, "marker")).toBe(uri); const init = fetcher.mock.calls[0][1] as RequestInit; expect(JSON.parse(init.body as string).status).toEqual({ privacyStatus: "private", selfDeclaredMadeForKids: false }); expect(init.body).not.toContain("publishAt"); });
it.each([[undefined, 0], ["bytes=0-262143", 262144]])("trusts confirmed 308 Range (%s)", async (range, offset) => { vi.stubGlobal("fetch", vi.fn<typeof fetch>(async () => new Response(null, { status: 308, headers: range ? { Range: String(range) } : {} }))); expect(await client().probe(uri, 262150)).toEqual({ offset }); });
it.each(["bytes=10-20", "bytes=0-999999"])("refuses invalid 308 offset (%s)", async range => { vi.stubGlobal("fetch", vi.fn<typeof fetch>(async () => new Response(null, { status: 308, headers: { Range: range } }))); await expect(client().probe(uri, 100)).rejects.toMatchObject({ code: "UPLOAD_RANGE" }); });
it("classifies incomplete final response as recoverable without replay", async () => { vi.stubGlobal("fetch", vi.fn<typeof fetch>(async () => new Response("{", { status: 201 }))); await expect(client().probe(uri, 100)).rejects.toMatchObject({ code: "UPLOAD_RESULT", retryable: true }); });
it("deduplicates video IDs and uses no pagination arguments in id mode", async () => { const fetcher = vi.fn<typeof fetch>(async () => Response.json({ items: [{ id: "v1" }] })); vi.stubGlobal("fetch", fetcher); expect(await client().list(["v1", "v2", "v1"])).toEqual([{ id: "v1" }]); const url = new URL(fetcher.mock.calls[0][0] as string); expect(url.searchParams.get("id")).toBe("v1,v2"); expect(url.searchParams.has("maxResults")).toBe(false); expect(url.searchParams.has("pageToken")).toBe(false); });
it("preserves other mutable fields while replacing metadata and setting private + future publishAt", async () => { const fetcher = vi.fn().mockResolvedValueOnce(Response.json({ items: [{ id: "v1", snippet: { title: "old", description: "old", channelId: "channel_one", defaultLanguage: "en", defaultAudioLanguage: "en" }, status: { privacyStatus: "private", publicStatsViewable: true } }] })).mockResolvedValueOnce(Response.json({})); vi.stubGlobal("fetch", fetcher); const job = fixtureJob(); job.profile.privacy = "public"; await client().finalize("v1", job, { title: "New", description: "Copy" }, "2026-12-01T00:00:00Z"); const body = JSON.parse(fetcher.mock.calls[1][1].body); expect(body.snippet).toMatchObject({ title: "New", defaultLanguage: "en", defaultAudioLanguage: "en" }); expect(body.status).toMatchObject({ publicStatsViewable: true, privacyStatus: "private", publishAt: "2026-12-01T00:00:00Z" }); expect(body.snippet.channelId).toBeUndefined(); });
it("refuses to unpublish a public video during cancellation", async () => { const fetcher = vi.fn<typeof fetch>(async () => Response.json({ items: [{ id: "v1", status: { privacyStatus: "public" } }] })); vi.stubGlobal("fetch", fetcher); await expect(client().unschedule("v1")).rejects.toMatchObject({ code: "ALREADY_PUBLIC" }); expect(fetcher).toHaveBeenCalledOnce(); });
it("checks playlist membership before another insert after an unknown result", async () => { const fetcher = vi.fn().mockResolvedValueOnce(Response.json({ items: [{ snippet: { channelId: "channel_one" } }] })).mockResolvedValueOnce(Response.json({ items: [{ id: "membership" }] })); vi.stubGlobal("fetch", fetcher); await client().playlist("v1", "PLsynthetic"); expect(fetcher).toHaveBeenCalledTimes(2); expect(fetcher.mock.calls.every(([, init]) => !init.method || init.method === "GET")).toBe(true); });
