/** 素材扫描不得读取视频，Hash 与路径逃逸采用真实临时文件验证。 */
import { beforeEach, afterEach, expect, it, vi } from "vitest";
import { mkdtemp, mkdir, writeFile, rm, symlink, utimes } from "node:fs/promises";
import { createReadStream } from "node:fs";
import os from "node:os"; import path from "node:path";
vi.mock("node:fs", async importOriginal => { const actual = await importOriginal<typeof import("node:fs")>(); return { ...actual, createReadStream: vi.fn(actual.createReadStream) }; });
import { scanPublishingAssets, validateAsset, resolvePublishingThumbnail } from "@/core/publishing/assets";
let root: string;
beforeEach(async () => { root = await mkdtemp(path.join(os.tmpdir(), "publishing-assets-")); await mkdir(path.join(root, "videos")); await mkdir(path.join(root, "music")); await mkdir(path.join(root, "thumbnails")); await writeFile(path.join(root, "videos", "clip10.mp4"), "large-video-placeholder"); await writeFile(path.join(root, "videos", "clip2.mp4"), "second-video"); });
afterEach(async () => { if (path.dirname(root) !== os.tmpdir() || !path.basename(root).startsWith("publishing-assets-")) throw new Error("Unsafe cleanup"); await rm(root, { recursive: true, force: true }); });
it("indexes stat/version and natural order with zero complete video reads", async () => { const index = await scanPublishingAssets(root); expect(index.assets.map(a => a.filename)).toEqual(["clip2.mp4", "clip10.mp4"]); expect(index.assets[0]).toMatchObject({ sha256: null, hashState: "not_computed" }); expect(createReadStream).not.toHaveBeenCalled(); const hash = await validateAsset(root, index.assets[0]); expect(hash.sha256).toMatch(/^[a-f0-9]{64}$/); expect(createReadStream).toHaveBeenCalledOnce(); });
it("detects different bytes even when size and mtime are restored", async () => { const [asset] = (await scanPublishingAssets(root)).assets; const first = await validateAsset(root, asset); const file = path.join(root, "videos", asset.filename); await writeFile(file, "changed-data"); await utimes(file, new Date(asset.mtimeMs), new Date(asset.mtimeMs)); await expect(validateAsset(root, asset, first.sha256)).rejects.toMatchObject({ code: "ASSET_CHANGED" }); });
it("rejects paths, non-images and thumbnail links outside the permitted directory", async () => { await expect(resolvePublishingThumbnail(root, "../escape.png")).rejects.toMatchObject({ code: "MEDIA" }); await writeFile(path.join(root, "thumbnails", "fake.png"), "not png"); await expect(resolvePublishingThumbnail(root, "fake.png")).rejects.toMatchObject({ code: "MEDIA" }); const outside = path.join(root, "external"); await mkdir(outside); await writeFile(path.join(outside, "image.png"), Buffer.from("89504e470d0a1a0a", "hex")); await symlink(outside, path.join(root, "thumbnails", "outside"), "junction"); await expect(resolvePublishingThumbnail(root, "outside/image.png")).rejects.toMatchObject({ code: "MEDIA" }); });
it("aborts hashing at shutdown without retaining a partial digest", async () => { const [asset] = (await scanPublishingAssets(root)).assets; const abort = new AbortController(); abort.abort(); await expect(validateAsset(root, asset, undefined, abort.signal)).rejects.toMatchObject({ name: "AbortError" }); });
