/** Cloud 集成覆盖真实权限、文件事务和投递；素材 RPC 用假 Agent 回应。 */
import { beforeEach, afterEach, expect, it, vi } from "vitest";
import { mkdtemp, rm } from "node:fs/promises"; import os from "node:os"; import path from "node:path"; import { randomUUID } from "node:crypto";
const remote = vi.hoisted(() => ({ scan: vi.fn() }));
vi.mock("@/cloud/tasks", async importOriginal => ({ ...await importOriginal<typeof import("@/cloud/tasks")>(), rpc: remote.scan }));
import { createPairing, pairAgent, openSession, heartbeatAgent, agentStore, setAgentOwner } from "@/cloud/agents";
import { cloudStore } from "@/cloud/store";
import { accessStore, emptyAccess } from "@/server/access";
import { publishingStore, acceptPublishingPrivacy, savePublishingPolicy, savePublishingProfile, previewPublishingBatch, confirmPublishingBatch, publishingView, publishingTick, reportPublishing, chargePublishing, requestPublishingCleanup, completePublishingCleanup, changePublishingJob } from "@/cloud/publishing";
import { defaultPolicy, PRIVACY_VERSION } from "@/shared/publishing";
import { fixtureJob } from "./publishing-fixtures";
let root: string; const alice = { username: "alice", role: "customer" as const }; const admin = { username: "admin", role: "admin" as const };
beforeEach(async () => { root = await mkdtemp(path.join(os.tmpdir(), "publishing-cloud-")); vi.useFakeTimers({ toFake: ["Date"] }); vi.setSystemTime(new Date("2026-10-01T00:00:00Z")); vi.stubEnv("LIVEPILOT_DATA_ROOT", root); vi.stubEnv("LIVEPILOT_ENCRYPTION_KEY", "a".repeat(64)); vi.stubEnv("LIVEPILOT_INSTANCES", "main"); const access = emptyAccess(); access.users.push(...[alice, admin].map(u => ({ ...u, salt: "synthetic", hash: "synthetic", revision: randomUUID(), disabled: false }))); await accessStore().write("access.json", access); const p = await createPairing("pc", "Synthetic", "alice"); await pairAgent("pc", p.code, "b".repeat(64)); const session = await openSession("pc", randomUUID(), [{ id: "main", name: "Main" }]); await heartbeatAgent("pc", session.session, []); await agentStore("pc").write("capabilities.json", ["publishing-v1"]); await cloudStore().write("bindings.json", [{ agentId: "pc", instanceId: "main", channelId: "channel_one", confirmed: true }]); await savePublishingPolicy(admin, { ...defaultPolicy, enabled: true, privacyContact: "synthetic@example.invalid" }); remote.scan.mockResolvedValue({ assets: [fixtureJob().asset], thumbnails: [], channelId: "channel_one", channel: "Test" }); });
afterEach(async () => { vi.useRealTimers(); vi.unstubAllEnvs(); if (path.dirname(root) !== os.tmpdir() || !path.basename(root).startsWith("publishing-cloud-")) throw new Error("Unsafe cleanup"); await rm(root, { recursive: true, force: true }); });
/** 确认一个私密发布批次；不会发起实际上传或公开。 */
async function batch() { await acceptPublishingPrivacy(alice, PRIVACY_VERSION); const profile = await savePublishingProfile(alice, fixtureJob().profile); return previewPublishingBatch(alice, profile.id, [fixtureJob().asset.id]); }
it("requires privacy consent and current device ownership", async () => { await expect(savePublishingProfile(alice, fixtureJob().profile)).rejects.toMatchObject({ code: "PRIVACY" }); const b = await batch(); await confirmPublishingBatch(alice, b.id, false, true); expect((await publishingView({ username: "bob", role: "customer" })).jobs).toEqual([]); await expect(changePublishingJob({ username: "bob", role: "customer" }, (await publishingView(alice)).jobs[0].spec.id, "cancel")).rejects.toMatchObject({ code: "FORBIDDEN" }); });
it("confirms idempotently with immutable Profile snapshot and explicit per-item copy", async () => { const b = await batch(); const jobs = await confirmPublishingBatch(alice, b.id, false, true, [{ assetId: b.assets[0].id, title: "Manual 🌙", description: "" }]); expect(jobs[0].spec.overrides).toEqual({ title: "Manual 🌙", description: "" }); const again = await confirmPublishingBatch(alice, b.id, false, true); expect(again[0].spec.id).toBe(jobs[0].spec.id); await savePublishingProfile(alice, { ...b.profile, revision: 2, titleTemplate: "Changed" }); expect((await publishingView(alice)).jobs[0].spec.profile.titleTemplate).toBe("{{filenameStem}}"); });
it("requires real public verification, preserves original schedule and dispatches only rolling window", async () => { await acceptPublishingPrivacy(alice, PRIVACY_VERSION); const profile = fixtureJob().profile; profile.privacy = "public"; profile.scheduled = true; remote.scan.mockResolvedValue({ assets: Array.from({ length: 100 }, (_, i) => ({ ...fixtureJob().asset, id: i.toString(16).padStart(64, "0"), version: i.toString(16).padStart(64, "0"), filename: `movie${i}.mp4` })), thumbnails: [], channelId: "channel_one" }); await savePublishingProfile(alice, profile); const b = await previewPublishingBatch(alice, profile.id, (await remote.scan()).assets.map((a: { id: string }) => a.id)); await expect(confirmPublishingBatch(alice, b.id, false, true)).rejects.toMatchObject({ code: "PUBLIC_UNVERIFIED" }); await savePublishingPolicy(admin, { ...defaultPolicy, enabled: true, publicVerified: true, privacyContact: "synthetic@example.invalid", verificationNote: "Synthetic test only" }); const jobs = await confirmPublishingBatch(alice, b.id, false, true); await publishingTick(); const queue = await agentStore("pc").read<{ records: unknown[] }>("tasks.json"); expect(queue?.records).toHaveLength(jobs.filter(j => Date.parse(j.spec.originalPublishAt!) <= Date.now() + 28 * 86400_000).length); const first = jobs[0]; await changePublishingJob(alice, first.spec.id, "reschedule", "2026-10-01T19:30:00Z"); const changed = (await publishingView(alice)).jobs[0]; expect(changed.initialPublishAt).toBe(first.spec.originalPublishAt); expect(changed.spec.originalPublishAt).toBe("2026-10-01T19:30:00Z"); });
it("stores sequence acknowledgements, rejects another agent and admits project budget idempotently", async () => { const b = await batch(); const [job] = await confirmPublishingBatch(alice, b.id, false, true); const report = { id: job.spec.id, revision: 1, sequence: 2, state: "uploading" as const, offset: 100, total: job.spec.asset.size, updatedAt: Date.now() }; await expect(reportPublishing("other", [report])).rejects.toMatchObject({ code: "REPORT" }); await reportPublishing("pc", [report]); await reportPublishing("pc", [{ ...report, sequence: 1, offset: 0 }]); expect((await publishingView(alice)).jobs[0].observed?.offset).toBe(100); await savePublishingPolicy(admin, { ...defaultPolicy, enabled: true, privacyContact: "synthetic@example.invalid", uploadsPerDay: 1, otherUnitsPerDay: 50 }); const receipt = randomUUID(); await chargePublishing("pc", job.spec.id, receipt, 50, true); await chargePublishing("pc", job.spec.id, receipt, 50, true); await expect(chargePublishing("pc", job.spec.id, randomUUID(), 1, false)).rejects.toMatchObject({ code: "VIDEO_QUOTA" }); await expect(chargePublishing("pc", job.spec.id, randomUUID(), 0, true)).rejects.toMatchObject({ code: "VIDEO_QUOTA" }); });
it("removes Cloud publishing data immediately but keeps cleanup pending until correct Agent confirmation", async () => { const b = await batch(); await confirmPublishingBatch(alice, b.id, false, true); const cleanup = await requestPublishingCleanup(alice, "pc", "main"); expect((await publishingView(alice)).jobs).toEqual([]); expect((await publishingView(alice)).cleanups[0].state).toBe("pending"); await expect(savePublishingProfile(alice, fixtureJob().profile)).rejects.toMatchObject({ code: "CLEANUP" }); await expect(completePublishingCleanup("other", cleanup.id)).rejects.toMatchObject({ code: "CLEANUP" }); await completePublishingCleanup("pc", cleanup.id); expect((await publishingView(alice)).cleanups[0].state).toBe("complete"); expect(await cloudStore().read("bindings.json")).toEqual([]); });
it("turns confirmed invalid authorization into a priority cleanup instead of continued uploads", async () => { const b = await batch(); const [job] = await confirmPublishingBatch(alice, b.id, false, true); await reportPublishing("pc", [{ id: job.spec.id, revision: 1, sequence: 1, state: "needs_attention", offset: 0, total: job.spec.asset.size, updatedAt: Date.now(), authorizationInvalid: true }]); expect((await publishingView(alice)).jobs).toEqual([]); expect((await publishingView(alice)).cleanups[0].state).toBe("pending"); expect(await publishingStore().read("state.json")).toBeTruthy(); });
it("reserves a complete publication before dispatch and exposes budget blocking separately", async () => { const b = await batch(); await confirmPublishingBatch(alice, b.id, false, true); await savePublishingPolicy(admin, { ...defaultPolicy, enabled: true, privacyContact: "synthetic@example.invalid", otherUnitsPerDay: 53 }); await publishingTick(); expect((await publishingView(alice)).jobs[0].blockReason).toContain("等待项目"); expect(await agentStore("pc").read("tasks.json")).toBeNull(); await savePublishingPolicy(admin, { ...defaultPolicy, enabled: true, privacyContact: "synthetic@example.invalid", otherUnitsPerDay: 54 }); await publishingTick(); expect((await publishingView(admin)).quota?.reserved).toEqual({ uploads: 1, units: 54 }); const job = (await publishingView(alice)).jobs[0]; await chargePublishing("pc", job.spec.id, randomUUID(), 0, true); expect((await publishingView(admin)).quota).toMatchObject({ uploads: 1, units: 0, reserved: { uploads: 0, units: 54 } }); await reportPublishing("pc", [{ id: job.spec.id, revision: job.spec.revision, sequence: 1, state: "completed", offset: job.spec.asset.size, total: job.spec.asset.size, updatedAt: Date.now() }]); expect((await publishingView(admin)).quota?.reserved).toEqual({ uploads: 0, units: 0 }); });
it("hides former-owner plans after device reassignment and blocks their new API admission", async () => { const b = await batch(); const [job] = await confirmPublishingBatch(alice, b.id, false, true); await setAgentOwner("pc", "bob"); const bob = { username: "bob", role: "customer" as const }; await acceptPublishingPrivacy(bob, PRIVACY_VERSION); expect((await publishingView(bob)).jobs).toEqual([]); expect((await publishingView(bob)).profiles).toEqual([]); await expect(chargePublishing("pc", job.spec.id, randomUUID(), 1, false)).rejects.toMatchObject({ code: "FORBIDDEN" }); });
