/** 真实服务端会话覆盖账号角色、所有目标入口和跨客户恢复，不模拟权限成功。 */
import { mkdtemp, rm } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import os from "node:os";import path from "node:path";
import { beforeEach, afterEach, it, expect, vi } from "vitest";
import { accessStore, emptyAccess, passwordHash, login, authenticate } from "@/server/access";
import { createPairing, pairAgent, listAgents, setAgentOwner } from "@/cloud/agents";
import { GET as instances } from "@/app/api/instances/route";
import { GET as status } from "@/app/api/status/route";
import { POST as control } from "@/app/api/control/route";
import { POST as upload, GET as uploads } from "@/app/api/uploads/route";
import { GET as uploadGet, PUT as chunk, DELETE as cancel } from "@/app/api/uploads/[id]/route";
import { POST as finish } from "@/app/api/uploads/[id]/complete/route";
import { POST as oauth } from "@/app/api/youtube/connect/route";
import { DELETE as remove } from "@/app/api/devices/route";
import { POST as pairing } from "@/app/api/agent/[...path]/route";
import { GET as admin } from "@/app/api/admin/overview/route";
import { GET as desktopCheck } from "@/app/api/desktop/session/route";
let root:string;let customer:string;let administrator:string;
/** 合成密码只存在测试目录，不使用真实生产凭据。 */
beforeEach(async()=>{root=await mkdtemp(path.join(os.tmpdir(),"ln-roles-"));vi.stubEnv("LIVEPILOT_DATA_ROOT",root);vi.stubEnv("LIVEPILOT_ACCESS_DIR",path.join(root,"access"));vi.stubEnv("LIVEPILOT_MODE","cloud");vi.stubEnv("LIVEPILOT_ORIGIN","https://cloud.example.com");const state=emptyAccess();const salt="b".repeat(32);const hash=(await passwordHash("synthetic-password",salt)).toString("hex");for(const username of ["Do","Liang","ULiang","UDo","Other"])state.users.push({username,role:username==="Liang"||username==="Other"?"customer":"admin",salt,hash,revision:"v1",disabled:false});await accessStore().write("access.json",state);customer=(await login("Liang","synthetic-password")).token;administrator=(await login("ULiang","synthetic-password")).token;await createPairing("pc_other","Other PC","Other");await createPairing("pc_mine","My PC","Liang");await createPairing("pc_legacy","Legacy");});
/** 仅清理本测试拥有的临时目录。 */
afterEach(async()=>{vi.unstubAllEnvs();if(path.dirname(root)!==os.tmpdir()||!path.basename(root).startsWith("ln-roles-"))throw new Error("Unsafe cleanup");await rm(root,{recursive:true,force:true});});
/** 同源浏览器请求携带实际会话，伪造目标由服务端拒绝。 */
function req(route:string,method="GET",body?:unknown,token=customer){return new Request("https://cloud.example.com/api/"+route,{method,headers:{host:"cloud.example.com",origin:"https://cloud.example.com","x-livepilot":"1","content-type":"application/json",cookie:"livepilot_session="+token},...(body===undefined?{}:{body:JSON.stringify(body)})});}
it("routes roles and permits only customer desktop sessions",async()=>{for(const username of ["ULiang","UDo"]){await expect(login(username,"synthetic-password",true)).rejects.toMatchObject({status:403});expect((await login(username,"synthetic-password")).user.role).toBe("admin");}expect((await login("Do","synthetic-password",true)).user.role).toBe("customer");const d=await login("Liang","synthetic-password",true);expect(d.user.role).toBe("customer");await expect(authenticate(req("session","GET",undefined,d.token))).rejects.toMatchObject({status:401});const r=new Request("https://cloud.example.com/api/desktop/session?agentId=pc_other",{headers:{host:"cloud.example.com",authorization:"Bearer "+d.token}});expect((await desktopCheck(r)).status).toBe(403);});
it("filters device inventories and protects admin overview",async()=>{expect((await (await instances(req("instances"))).json()).agents.map((a:{id:string})=>a.id)).toEqual(["pc_mine"]);expect((await admin(req("admin/overview"))).status).toBe(403);expect((await admin(req("admin/overview","GET",undefined,administrator))).status).toBe(200);});
it("denies other customer at every read, write, upload and OAuth entry",async()=>{const q="?agentId=pc_other&instanceId=main";const context={params:Promise.resolve({id:randomUUID()})};const checks=[status(req("status"+q)),control(req("control","POST",{agentId:"pc_other",instanceId:"main",requestId:randomUUID(),action:"launch"})),upload(req("uploads","POST",{agentId:"pc_other",instanceId:"main",kind:"videos",filename:"test.mp4",size:10,fingerprint:"a".repeat(64)})),uploads(req("uploads"+q)),uploadGet(req("uploads/id"+q),context),chunk(req("uploads/id"+q,"PUT",{}),context),cancel(req("uploads/id"+q,"DELETE"),context),finish(req("uploads/id/complete"+q,"POST",{}),context),oauth(req("youtube/connect","POST",{agentId:"pc_other",instanceId:"main"})),remove(req("devices","DELETE",{agentId:"pc_other",confirmed:true}))];for(const response of await Promise.all(checks))expect(response.status).toBe(403);});
it("requires desktop customer bearer, refuses cross-owner recovery and keeps legacy unassigned",async()=>{const invitation=await createPairing("pc_invite","Invite","Liang");expect((await login("Do","synthetic-password",true)).user.role).toBe("customer");const d=await login("Liang","synthetic-password",true);const body={protocol:1,agentId:invitation.agentId,code:invitation.code,token:"b".repeat(64)};const headers={host:"cloud.example.com","content-type":"application/json"};const send=(extra:Record<string,string>,value=body)=>pairing(new Request("https://cloud.example.com/api/agent/pair",{method:"POST",headers:{...headers,...extra},body:JSON.stringify(value)}),{params:Promise.resolve({path:["pair"]})});expect((await send({})).status).toBe(401);expect((await send({authorization:"Bearer "+d.token})).status).toBe(200);const other=await createPairing("pc_cross","Cross","Other");expect((await send({authorization:"Bearer "+d.token},{...body,agentId:other.agentId,code:other.code})).status).toBe(403);expect((await listAgents()).find(a=>a.id==="pc_legacy")?.owner).toBeUndefined();await setAgentOwner("pc_legacy","Liang");expect((await listAgents()).find(a=>a.id==="pc_legacy")?.owner).toBe("Liang");await expect(pairAgent(other.agentId,other.code,"b".repeat(64),"pc_invite","Other")).rejects.toMatchObject({status:403});});
