/** 管理员总览：新鲜度、筛选、旧设备分配与客户工作台入口。 */
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { api } from "../client-request";
import type { overview } from "@/cloud/overview";
type Overview = Awaited<ReturnType<typeof overview>>;
/** 5 秒轮询不覆盖筛选，失败保留上次数据但明确过期。 */
export default function Admin() {
 const [data,setData] = useState<Overview>(); const [error,setError] = useState(""); const [customer,setCustomer] = useState(""); const [device,setDevice] = useState(""); const [status,setStatus] = useState(""); const [busy,setBusy] = useState(false); const [notice,setNotice] = useState("");
 useEffect(() => { let active=true; let loading=false; async function load(){ if(loading)return; loading=true; try {const next=await api<Overview>("/api/admin/overview"); if(active){setData(next);setError("");}}catch(e){if(active)setError((e as Error).message);}finally{loading=false;}} void load();const timer=setInterval(()=>void load(),5000);return()=>{active=false;clearInterval(timer);}; },[]);
 /** 分配完成重新读取状态；服务端再次验证空闲和客户角色。 */
 async function assign(agentId:string,owner:string){setBusy(true);setNotice("");try{await api("/api/admin/assign",{method:"POST",headers:{"Content-Type":"application/json","X-LivePilot":"1"},body:JSON.stringify({agentId,owner})});setData(await api<Overview>("/api/admin/overview"));setNotice("设备已分配，原配置和频道已保留。");}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 const rows=data?.rows.filter(r=>(!customer||(customer==="unassigned"?!r.customer:r.customer===customer))&&(!device||r.agentId===device)&&(!status||(status==="live"?r.streaming===true:status==="unknown"?r.streaming===null:status==="error"?!!r.error:r.streaming===false)));
 return <main className="main-wrapper admin-page" id="workspace"><div className="workspace-heading"><div><h1>管理员总览</h1><p>查看所有客户的直播与设备状态</p></div><Link href="/workspace">进入直播工作台 ↗</Link></div>{error&&<div className="banner error" role="alert">{error} · 以下为上次获取的数据，不能视为实时状态。</div>}{!data?<p role="status">正在读取设备状态…</p>:<>
 <div className="admin-metrics">{[["正在推流",data.totals.live],["在线电脑",data.totals.online],["离线电脑",data.totals.offline],["客户",data.totals.customers],["异常实例",data.totals.errors],["状态未知",data.totals.unknown]].map(([label,value])=><section key={label}><span>{label}</span><strong>{error?"—":value}</strong></section>)}</div><p className="admin-caption">每 5 秒刷新 · 超过 20 秒未更新的状态显示为未知 · OBS 推流与 YouTube 场次状态分别显示</p>
 <div className="admin-filters"><label>客户<select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">全部客户</option><option value="unassigned">待分配</option>{data.customers.map(c=><option key={c.username}>{c.username}</option>)}</select></label><label>电脑<select value={device} onChange={e=>setDevice(e.target.value)}><option value="">全部电脑</option>{data.agents.filter(a=>!a.revoked).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>状态<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option><option value="live">正在推流</option><option value="idle">未推流</option><option value="unknown">未知</option><option value="error">异常</option></select></label></div>
 <div className="admin-table-wrap"><table className="admin-table"><thead><tr>{["客户 / 电脑 / OBS","频道","OBS 状态","持续时间","YouTube 场次","最近心跳","最近操作人","处理"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows?.map(r=><tr key={r.agentId+":"+r.instanceId}><td>{r.customer||"待分配"}<br/>{r.device} / {r.name}</td><td>{r.channel||"未连接"}</td><td>{error||r.streaming===null?"未知":r.streaming?"正在推流":"未推流"}{r.error&&<small>{r.error}</small>}</td><td>{r.streaming&&r.durationMs!==undefined?Math.floor(r.durationMs/60000)+" 分钟":"—"}</td><td>{r.lifecycle||"—"}</td><td>{r.lastSeen?new Date(r.lastSeen).toLocaleString():"未上线"}</td><td>{r.actor||"—"}</td><td><Link href={"/workspace?customer="+encodeURIComponent(r.customer||"")+"#instance-"+r.agentId+"-"+r.instanceId}>协助操作</Link></td></tr>)}</tbody></table>{!rows?.length&&<p>当前筛选下没有 OBS 实例。</p>}</div>
 <section className="admin-assignment"><h2>设备归属</h2><p>旧设备先由管理员分配。更改已配对电脑的归属，需要电脑在线且直播、上传和授权均已结束。</p>{notice&&<p role="status">{notice}</p>}{data.agents.filter(a=>!a.pairedTo).map(a=><form key={a.id} onSubmit={e=>{e.preventDefault();void assign(a.id,String(new FormData(e.currentTarget).get("owner")));}}><span>{a.name} · {a.owner||"待分配"}{a.revoked?" · 已移除":""}</span><label>所属客户<select name="owner" defaultValue={a.owner||""} required><option value="" disabled>选择客户</option>{data.customers.map(c=><option key={c.username}>{c.username}</option>)}</select></label><button disabled={busy}>分配</button></form>)}</section></>}
 </main>;
}
