/** 根据经过校验的 origin 生成 Nginx/systemd；仅写输出目录，不操作线上服务。 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { readEnv, originDomain } from "./config.mjs";
/** 分离 HTTP 验证和 HTTPS 阶段；显式域名匹配避免首次签发落到发行版默认站点。 */
export function nginxConfig(domain, tls = false) {
  originDomain(`https://${domain}`);
  const http = `# Generated by LivePilot; OAuth query strings must not enter access logs.\nserver {\n listen 80;\n server_name ${domain};\n access_log off;\n location /.well-known/acme-challenge/ { root /var/www/livepilot-acme; }\n location / { ${tls ? `return 308 https://${domain}$request_uri;` : "return 503;"} }\n}\n`;
  if (!tls) return http;
  return http + `server {\n listen 443 ssl;\n server_name ${domain};\n ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;\n ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;\n ssl_protocols TLSv1.2 TLSv1.3;\n access_log off;\n client_max_body_size 8m;\n client_body_timeout 120s;\n location / {\n  proxy_pass http://127.0.0.1:3010;\n  proxy_set_header Host $host;\n  proxy_set_header X-Forwarded-Proto https;\n  proxy_http_version 1.1;\n  proxy_buffering off;\n  proxy_request_buffering off;\n  proxy_read_timeout 180s;\n  proxy_send_timeout 180s;\n }\n}\n`;
}
/** Linux 可执行路径必须是无空白的绝对路径，不允许 unit 指令注入。 */
export function executable(value) { if (!/^\/[a-zA-Z0-9_./-]+$/.test(value)) throw new Error("Node/Certbot 必须为不含空白的 Linux 绝对路径。"); return value; }
/** 固定单进程持久数据目录；云端无需 OBS/Google 机密。 */
export function serviceUnit(node) { return `# LivePilot cloud controller\n[Unit]\nDescription=LivePilot cloud controller\nAfter=network-online.target\nWants=network-online.target\n[Service]\nType=simple\nUser=livepilot\nGroup=livepilot\nWorkingDirectory=/opt/livepilot/current\nEnvironmentFile=/etc/livepilot/cloud.env\nExecStart=${executable(node)} node_modules/next/dist/bin/next start --hostname 127.0.0.1 --port 3010\nRestart=on-failure\nRestartSec=5\nTimeoutStopSec=60\nNoNewPrivileges=true\nPrivateTmp=true\nProtectSystem=full\nProtectHome=true\nUMask=0077\n[Install]\nWantedBy=multi-user.target\n`; }
/** 验证配置后仅生成模板；域名与密钥始终从用户私有环境读取。 */
export async function render(envFile, out, node, certbot) {
  const env = await readEnv(envFile); const domain = originDomain(env.LIVEPILOT_ORIGIN);
  if (env.LIVEPILOT_MODE !== "cloud" || env.LIVEPILOT_DATA_ROOT !== "/var/lib/livepilot/data" || !/^[a-f0-9]{64}$/i.test(env.LIVEPILOT_ENCRYPTION_KEY || "")) throw new Error("需要 cloud 模式、固定持久目录及 64 位十六进制密钥。");
  await mkdir(out, { recursive: true });
  const files = { "nginx-http.conf": nginxConfig(domain), "nginx-https.conf": nginxConfig(domain, true), "livepilot.service": serviceUnit(node), "livepilot-cert-renew.service": `# Renew domain certificate and reload validated Nginx\n[Unit]\nDescription=Renew LivePilot HTTPS certificates\n[Service]\nType=oneshot\nExecStart=${executable(certbot)} renew --quiet --deploy-hook "nginx -t && systemctl reload nginx"\n` };
  for (const [name, value] of Object.entries(files)) await writeFile(path.join(out, name), value);
  return domain;
}
/** 命令行入口仅输出公共域名，生成文件不含环境密钥。 */
if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  try { const { values: a } = parseArgs({ options: { env: { type: "string", default: ".env.cloud" }, out: { type: "string", default: ".data/deployment/generated" }, node: { type: "string", default: "/usr/bin/node" }, certbot: { type: "string", default: "/usr/bin/certbot" } } }); console.log(await render(a.env, a.out, a.node, a.certbot)); }
  catch { console.error("部署模板生成失败，请检查 cloud 环境、域名及路径。"); process.exitCode = 1; }
}
